### ISSUE TITLE
Scrutinizer config and coverage

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#160]
Don't you want to enable coverage in Scrutinizer?

Also, scrutinizer should be limited to inspect only the src/ directory, not any other.

I usually use this configuration file:

```yml
filter:
  paths: [src/*]
tools:
  php_analyzer: true
  php_mess_detector: true
  php_pdepend: true
  external_code_coverage:
    timeout: '600'
```

**Comment by henrikbjorn** [comment]
Dont really care about code coverage, the tests and specs themselves should give us confidence enough in our code.

Have incorporated some from your config and it is now 

``` yaml
tools:
    php_pdepend: true
    php_cs_fixer: true
    php_sim: true
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer:
        config:
            standard: PSR2

filter:
    paths: [src/*]
```
